-- =====================================================
-- CATALOGO COMPLETO 3DZAAP - v3.0 FINAL
-- 118 modelos | 48 local WebP | 17 CDN | 53 sem imagem
-- ORDEM: 1) fix_duplicates.sql  2) este ficheiro
-- =====================================================

-- O comando DELETE foi removido para proteger as Foreign Keys.
-- Em vez disso, utilizamos o ON CONFLICT (UPSERT) para atualizar imagens de modelos existentes!

INSERT INTO public.printer_models (brand, name, type, image_url)
VALUES
('Bambu Lab','X1 Carbon','fdm','images/printers/bambu_lab_x1_carbon.webp'),
('Bambu Lab','X1E','fdm','images/printers/bambu_lab_x1_carbon.webp'),
('Bambu Lab','P1S','fdm','images/printers/bambu_lab_p1s.webp'),
('Bambu Lab','P1P','fdm','images/printers/bambu_lab_p1p.webp'),
('Bambu Lab','A1','fdm','images/printers/bambu_lab_a1.webp'),
('Bambu Lab','A1 Mini','fdm','images/printers/bambu_lab_a1_mini.webp'),
('Bambu Lab','A1 Mini Combo','fdm','images/printers/bambu_lab_a1_mini.webp'),
('Bambu Lab','H2D','fdm','images/printers/bambu_lab_a1_mini.webp'),
('Bambu Lab','H2S','fdm','images/printers/bambu_lab_a1_mini.webp'),
('Bambu Lab','H2C','fdm','images/printers/bambu_lab_a1_mini.webp'),
('Prusa Research','MK4','fdm','images/printers/prusa_research_mk4s.webp'),
('Prusa Research','MK4S','fdm','images/printers/prusa_research_mk4s.webp'),
('Prusa Research','Mini+','fdm','images/printers/prusa_research_mk4s.webp'),
('Prusa Research','XL','fdm','images/printers/prusa_research_xl.webp'),
('Prusa Research','XL Multi-Tool','fdm','images/printers/prusa_research_xl.webp'),
('Prusa Research','Core One','fdm','images/printers/prusa_research_mk4s.webp'),
('Prusa Research','SL1S Speed','resina','images/printers/prusa_research_mk4s.webp'),
('Creality','Ender-3 V3 SE','fdm','images/printers/creality_ender3_v3_se.webp'),
('Creality','Ender-3 V3 KE','fdm','images/printers/creality_ender3_v3_se.webp'),
('Creality','Ender-3 V3','fdm','images/printers/creality_ender3_v3_se.webp'),
('Creality','Ender-3 V3 Plus','fdm','images/printers/creality_ender3_v3_se.webp'),
('Creality','K1','fdm','images/printers/creality_k1c.webp'),
('Creality','K1 SE','fdm','images/printers/creality_k1c.webp'),
('Creality','K1C','fdm','images/printers/creality_k1c.webp'),
('Creality','K1 Max','fdm','images/printers/creality_k1_max.webp'),
('Creality','K2','fdm','images/printers/creality_k1_max.webp'),
('Creality','K2 Plus','fdm','images/printers/creality_k1_max.webp'),
('Creality','Creality Hi','fdm','images/printers/creality_k1c.webp'),
('Creality','Halot One Plus','resina','images/printers/creality_ender3_v3_se.webp'),
('Creality','Halot Mage','resina','images/printers/creality_ender3_v3_se.webp'),
('Creality','Halot Mage Pro','resina','images/printers/creality_ender3_v3_se.webp'),
('Anycubic','Kobra 2','fdm','images/printers/anycubic_kobra_2_pro.webp'),
('Anycubic','Kobra 2 Pro','fdm','images/printers/anycubic_kobra_2_pro.webp'),
('Anycubic','Kobra 2 Max','fdm','images/printers/anycubic_kobra_2_pro.webp'),
('Anycubic','Kobra 3','fdm','images/printers/anycubic_kobra_2_pro.webp'),
('Anycubic','Kobra 3 Max','fdm','images/printers/anycubic_kobra_2_pro.webp'),
('Anycubic','Kobra S1','fdm','images/printers/anycubic_kobra_s1_max.webp'),
('Anycubic','Kobra S1 Max','fdm','images/printers/anycubic_kobra_s1_max.webp'),
('Anycubic','Kobra X','fdm','images/printers/anycubic_kobra_x.webp'),
('Anycubic','Photon Mono M5s','resina',NULL),
('Anycubic','Photon Mono M7','resina',NULL),
('Anycubic','Photon Mono M7 Pro','resina',NULL),
('Anycubic','Photon Mono M7 Max','resina',NULL),
('Anycubic','Photon P1','resina',NULL),
('Elegoo','Neptune 4','fdm','images/printers/elegoo_neptune_4_max.webp'),
('Elegoo','Neptune 4 Pro','fdm','images/printers/elegoo_neptune_4_max.webp'),
('Elegoo','Neptune 4 Plus','fdm','images/printers/elegoo_neptune_4_max.webp'),
('Elegoo','Neptune 4 Max','fdm','images/printers/elegoo_neptune_4_max.webp'),
('Elegoo','Centauri Carbon','fdm','images/printers/elegoo_centauri_carbon.webp'),
('Elegoo','OrangeStorm Giga','fdm','images/printers/elegoo_orangestorm_giga.webp'),
('Elegoo','Saturn 3 Ultra','resina','images/printers/elegoo_saturn_3_ultra.webp'),
('Elegoo','Saturn 4','resina','images/printers/elegoo_saturn_4_ultra.webp'),
('Elegoo','Saturn 4 Ultra','resina','images/printers/elegoo_saturn_4_ultra.webp'),
('Elegoo','Saturn 4 Ultra 16K','resina','images/printers/elegoo_saturn_4_ultra.webp'),
('Elegoo','Mars 4','resina','images/printers/elegoo_mars_4_ultra.webp'),
('Elegoo','Mars 4 Ultra','resina','images/printers/elegoo_mars_4_ultra.webp'),
('Elegoo','Mars 5','resina','images/printers/elegoo_mars_5.webp'),
('Elegoo','Mars 5 Ultra','resina','images/printers/elegoo_mars_5.webp'),
('FlashForge','Adventurer 5M','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Adventurer 5M Pro','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Adventurer 5M Lite','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Creator 4S','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Creator 5','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Guider 3 Plus','fdm','images/printers/flashforge_adventurer_5m.webp'),
('FlashForge','Focus 8.9','resina','images/printers/flashforge_adventurer_5m.webp'),
('QIDI Tech','X-Max 3','fdm','images/printers/qidi3d_X_MAX_3.webp'),
('QIDI Tech','X-Plus 3','fdm','images/printers/qidi3d_X_MAX_3.webp'),
('QIDI Tech','X-Smart 3','fdm','images/printers/qidi3d_X_MAX_3.webp'),
('QIDI Tech','Q1 Pro','fdm','images/printers/qidi3d_Q1_Pro_591c966d_92ef_4d39_83b6_c810ecdb5ed2.webp'),
('QIDI Tech','Plus4','fdm','images/printers/qidi3d_PLUS4_a838191a_7fc5_49d6_a245_4fb88c793490.webp'),
('Snapmaker','Snapmaker 2.0 A150','fdm',NULL),
('Snapmaker','Snapmaker 2.0 A250','fdm',NULL),
('Snapmaker','Snapmaker 2.0 A350','fdm',NULL),
('Snapmaker','Artisan','fdm',NULL),
('Snapmaker','J1s','fdm',NULL),
('Snapmaker','U1','fdm',NULL),
('Voron Design','Voron 0.2','fdm',NULL),
('Voron Design','Voron Trident','fdm',NULL),
('Voron Design','Voron 2.4','fdm',NULL),
('Voron Design','Voron Switchwire','fdm',NULL),
('Raise3D','Pro3','fdm',NULL),
('Raise3D','Pro3 Plus','fdm',NULL),
('Raise3D','E2','fdm',NULL),
('Raise3D','E2CF','fdm',NULL),
('Raise3D','N4','fdm',NULL),
('Ultimaker','S3','fdm',NULL),
('Ultimaker','S5','fdm',NULL),
('Ultimaker','S7','fdm',NULL),
('Artillery','Sidewinder X4 Pro','fdm',NULL),
('Artillery','Genius Pro','fdm',NULL),
('Artillery','Hornet','fdm',NULL),
('Sovol','SV06','fdm','images/printers/sovol_sv06.webp'),
('Sovol','SV06 Plus','fdm','images/printers/sovol_sv06.webp'),
('Sovol','SV07','fdm','images/printers/sovol_sv06.webp'),
('Sovol','SV08','fdm','images/printers/sovol_sv06.webp'),
('Phrozen','Sonic Mini 8K','resina','images/printers/phrozen_sonic_mini_8k.webp'),
('Phrozen','Sonic Mega 8K','resina','images/printers/phrozen_sonic_mini_8k.webp'),
('Phrozen','Sonic Mighty 8K','resina','images/printers/phrozen_sonic_mini_8k.webp'),
('Phrozen','Transform 12K','resina','images/printers/phrozen_sonic_mini_8k.webp'),
('Formlabs','Form 3','resina','images/printers/formlabs_form_3.webp'),
('Formlabs','Form 3+','resina','images/printers/formlabs_form_3.webp'),
('Formlabs','Form 3L','resina','images/printers/formlabs_form_3.webp'),
('Formlabs','Form 4','resina','images/printers/formlabs_form_3.webp'),
('Formlabs','Form 4L','resina','images/printers/formlabs_form_3.webp'),
('Zortrax','M200 Plus','fdm',NULL),
('Zortrax','M300 Dual','fdm',NULL),
('Zortrax','E3','fdm',NULL),
('Zortrax','Inkspire 2','resina',NULL),
('BCN3D','Epsilon W27','fdm',NULL),
('BCN3D','Epsilon W50','fdm',NULL),
('BCN3D','Omega I60','fdm',NULL),
('Stratasys','F123CR','fdm',NULL),
('Stratasys','F370CR','fdm',NULL),
('Stratasys','Fortus 380','fdm',NULL),
('Stratasys','Origin One','resina',NULL),
('MakerBot','METHOD X','fdm',NULL),
('MakerBot','METHOD XL','fdm',NULL),
('MakerBot','SKETCH','fdm',NULL)
ON CONFLICT (brand, name, type) 
DO UPDATE SET image_url = EXCLUDED.image_url;
