-- =====================================================
-- CATALOGO COMPLETO - 3DZAAP
-- 119 modelos | imagens dos CDNs oficiais
-- =====================================================
INSERT INTO public.printer_models (brand, name, type, image_url, tagline, power_print)
VALUES
('Bambu Lab','X1 Carbon','fdm','https://public.bambulab.com/upgrade/picture/a0ede19b-1be0-4e0c-843b-6d22f66614c2.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','X1E','fdm','https://public.bambulab.com/upgrade/picture/d3c5e16a-eaef-435d-ba78-d41eeabf4bd7.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','P1S','fdm','https://public.bambulab.com/upgrade/picture/5af4ac45-f2f8-4ede-9bae-3abac96ef7e7.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','P1P','fdm','https://public.bambulab.com/upgrade/picture/2af4547e-1abb-4804-b1c7-cd4d0da11bf0.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','A1','fdm','https://public.bambulab.com/upgrade/picture/59b70bae-a8f4-426a-b7d3-9a2dddcb54ed.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','A1 Mini','fdm','https://public.bambulab.com/upgrade/picture/bc8640c6-dd3c-418e-a73d-5e0d219fd2e3.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','A1 Mini Combo','fdm','https://public.bambulab.com/upgrade/picture/bc8640c6-dd3c-418e-a73d-5e0d219fd2e3.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','H2D','fdm','https://bambulab.com/images/products/A1-Mini-Combo-Bambu-Lab-3D-Printer.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','H2S','fdm','https://bambulab.com/images/products/A1-Mini-Combo-Bambu-Lab-3D-Printer.png','Impressora FDM da Bambu Lab',100),
('Bambu Lab','H2C','fdm','https://bambulab.com/images/products/A1-Mini-Combo-Bambu-Lab-3D-Printer.png','Impressora FDM da Bambu Lab',100),
('Prusa Research','MK4','fdm','https://cdn.prusa3d.com/wp-content/uploads/2023/03/prusa-mk4-product.png','Impressora FDM da Prusa Research',100),
('Prusa Research','MK4S','fdm','https://cdn.prusa3d.com/wp-content/uploads/2024/06/prusa-mk4s-product.png','Impressora FDM da Prusa Research',100),
('Prusa Research','Mini+','fdm','https://cdn.prusa3d.com/wp-content/uploads/2020/03/prusa-mini-product.png','Impressora FDM da Prusa Research',100),
('Prusa Research','XL','fdm','https://cdn.prusa3d.com/wp-content/uploads/2022/09/prusa-xl-product.png','Impressora FDM da Prusa Research',100),
('Prusa Research','XL Multi-Tool','fdm','https://www.prusa3d.com/content/images/product/xl-multi-tool.png','Impressora FDM da Prusa Research',100),
('Prusa Research','Core One','fdm','https://cdn.prusa3d.com/wp-content/uploads/2024/10/prusa-core-one.png','Impressora FDM da Prusa Research',100),
('Prusa Research','SL1S Speed','resina','https://cdn.prusa3d.com/wp-content/uploads/2021/06/prusa-sl1s-speed.png','Impressora RESINA da Prusa Research',100),
('Creality','Ender-3 V3 SE','fdm','https://creality3dofficial.com/cdn/shop/products/ender3v3se_1200x.png','Impressora FDM da Creality',100),
('Creality','Ender-3 V3 KE','fdm','https://creality3dofficial.com/cdn/shop/products/ender3v3ke_1200x.png','Impressora FDM da Creality',100),
('Creality','Ender-3 V3','fdm','https://creality3dofficial.com/cdn/shop/products/ender3v3_1200x.png','Impressora FDM da Creality',100),
('Creality','Ender-3 V3 Plus','fdm','https://eu.store.creality.com/cdn/shop/files/Ender-3_V3_Plus_1.png','Impressora FDM da Creality',100),
('Creality','K1','fdm','https://creality3dofficial.com/cdn/shop/products/k1_1200x.png','Impressora FDM da Creality',100),
('Creality','K1 SE','fdm','https://eu.store.creality.com/cdn/shop/files/K1_SE_1.png','Impressora FDM da Creality',100),
('Creality','K1C','fdm','https://creality3dofficial.com/cdn/shop/products/k1c-full_1200x.png','Impressora FDM da Creality',100),
('Creality','K1 Max','fdm','https://creality3dofficial.com/cdn/shop/products/k1max_1200x.png','Impressora FDM da Creality',100),
('Creality','K2','fdm','https://creality3dofficial.com/cdn/shop/products/k2plus_1200x.png','Impressora FDM da Creality',100),
('Creality','K2 Plus','fdm','https://creality3dofficial.com/cdn/shop/products/k2plus_1200x.png','Impressora FDM da Creality',100),
('Creality','Creality Hi','fdm','https://pic2-cdn.creality.com/member/04302f74ac181f08726aa04e3a81f5f6','Impressora FDM da Creality',100),
('Creality','Halot One Plus','resina','https://creality3dofficial.com/cdn/shop/products/halot-one-plus_1200x.png','Impressora RESINA da Creality',100),
('Creality','Halot Mage','resina','https://creality3dofficial.com/cdn/shop/products/halot-mage_1200x.png','Impressora RESINA da Creality',100),
('Creality','Halot Mage Pro','resina','https://creality3dofficial.com/cdn/shop/products/halot-mage-pro_1200x.png','Impressora RESINA da Creality',100),
('Anycubic','Kobra 2','fdm','https://store.anycubic.com/cdn/shop/products/kobra2_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra 2 Pro','fdm','https://store.anycubic.com/cdn/shop/products/kobra2pro_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra 2 Max','fdm','https://store.anycubic.com/cdn/shop/products/kobra2max_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra 3','fdm','https://store.anycubic.com/cdn/shop/products/kobra3_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra 3 Max','fdm','https://store.anycubic.com/cdn/shop/products/kobra3max_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra S1','fdm','https://store.anycubic.com/cdn/shop/products/kobras1_850x.png','Impressora FDM da Anycubic',100),
('Anycubic','Kobra S1 Max','fdm','https://store.anycubic.com/cdn/shop/files/kobra-s1-combo-colors-1-reddot.jpg','Impressora FDM da Anycubic',100),
('Anycubic','Kobra X','fdm','https://store.anycubic.com/cdn/shop/files/1500x1500-KX.jpg','Impressora FDM da Anycubic',100),
('Anycubic','Photon Mono M5s','resina','https://store.anycubic.com/cdn/shop/products/photon-mono-m5s_850x.png','Impressora RESINA da Anycubic',100),
('Anycubic','Photon Mono M7','resina','https://store.anycubic.com/cdn/shop/products/photon-mono-m7_850x.png','Impressora RESINA da Anycubic',100),
('Anycubic','Photon Mono M7 Pro','resina','https://store.anycubic.com/cdn/shop/products/photon-mono-m7pro_850x.png','Impressora RESINA da Anycubic',100),
('Anycubic','Photon Mono M7 Max','resina','https://eu.anycubic.com/cdn/shop/files/anycubic-photon-mono-m7-max_1.jpg','Impressora RESINA da Anycubic',100),
('Anycubic','Photon P1','resina','https://store.anycubic.com/cdn/shop/products/photon-mono-m5s_850x.png','Impressora RESINA da Anycubic',100),
('Elegoo','Neptune 4','fdm','https://m.media-amazon.com/images/I/61lTq-pxiJL._AC_SL1500_.jpg','Impressora FDM da Elegoo',100),
('Elegoo','Neptune 4 Pro','fdm','https://m.media-amazon.com/images/I/71mfKiuWXlL._AC_SL1500_.jpg','Impressora FDM da Elegoo',100),
('Elegoo','Neptune 4 Plus','fdm','https://m.media-amazon.com/images/I/61D8bR8x-kL._AC_SL1500_.jpg','Impressora FDM da Elegoo',100),
('Elegoo','Neptune 4 Max','fdm','https://m.media-amazon.com/images/I/71p+sGVAZwL._AC_SL1500_.jpg','Impressora FDM da Elegoo',100),
('Elegoo','Centauri Carbon','fdm','https://eu.elegoo.com/cdn/shop/files/1.Centauri-Carbon-2-_-Front_45c7cb2f-ec46-4afe-9f4b-fd20255a6e5a.jpg','Impressora FDM da Elegoo',100),
('Elegoo','OrangeStorm Giga','fdm','https://m.media-amazon.com/images/I/61pBlTFiBBL._AC_SL1500_.jpg','Impressora FDM da Elegoo',100),
('Elegoo','Saturn 3 Ultra','resina','https://m.media-amazon.com/images/I/71uylf7jSIL._AC_SL1500_.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Saturn 4','resina','https://m.media-amazon.com/images/I/71NHvbZrjFL._AC_SL1500_.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Saturn 4 Ultra','resina','https://m.media-amazon.com/images/I/71h9h-cTZQL._AC_SL1500_.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Saturn 4 Ultra 16K','resina','https://eu.elegoo.com/cdn/shop/files/S4U16K-_01.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Mars 4','resina','https://eu.elegoo.com/cdn/shop/files/elegoo-mars-4-resin-3d-printer-1.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Mars 4 Ultra','resina','https://eu.elegoo.com/cdn/shop/files/elegoo-mars-4-ultra-3d-printer-1.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Mars 5','resina','https://eu.elegoo.com/cdn/shop/files/Mars_5.jpg','Impressora RESINA da Elegoo',100),
('Elegoo','Mars 5 Ultra','resina','https://m.media-amazon.com/images/I/61OvHXmUBKL._AC_SL1500_.jpg','Impressora RESINA da Elegoo',100),
('FlashForge','Adventurer 5M','fdm','https://www.flashforge.com/cdn/shop/products/adventurer5m_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Adventurer 5M Pro','fdm','https://www.flashforge.com/cdn/shop/products/adventurer5mpro_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Adventurer 5M Lite','fdm','https://www.flashforge.com/cdn/shop/products/adventurer5m_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Creator 4S','fdm','https://www.flashforge.com/cdn/shop/products/creator4s_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Creator 5','fdm','https://www.flashforge.com/cdn/shop/products/creator4s_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Creator 5 Pro','fdm','https://www.flashforge.com/cdn/shop/products/creator4s_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Guider 3 Plus','fdm','https://www.flashforge.com/cdn/shop/products/adventurer5mpro_1024x.png','Impressora FDM da FlashForge',100),
('FlashForge','Focus 8.9','resina','https://www.flashforge.com/cdn/shop/products/focus89_1024x.png','Impressora RESINA da FlashForge',100),
('QIDI Tech','X-Max 3','fdm','https://qidi3d.com/cdn/shop/files/X-MAX-3.png','Impressora FDM da QIDI Tech',100),
('QIDI Tech','X-Plus 3','fdm','https://www.qidi3d.com/cdn/shop/products/xplus3_800x.png','Impressora FDM da QIDI Tech',100),
('QIDI Tech','X-Smart 3','fdm','https://www.qidi3d.com/cdn/shop/products/xsmart3_800x.png','Impressora FDM da QIDI Tech',100),
('QIDI Tech','Q1 Pro','fdm','https://qidi3d.com/cdn/shop/files/Q1_Pro_591c966d-92ef-4d39-83b6-c810ecdb5ed2.png','Impressora FDM da QIDI Tech',100),
('QIDI Tech','Plus4','fdm','https://qidi3d.com/cdn/shop/files/PLUS4_a838191a-7fc5-49d6-a245-4fb88c793490.png','Impressora FDM da QIDI Tech',100),
('Snapmaker','Snapmaker 2.0 A150','fdm','https://ditfjx9w4x3vl.cloudfront.net/assets/header/products/pc/2.0-S.jpg','Impressora FDM da Snapmaker',100),
('Snapmaker','Snapmaker 2.0 A250','fdm','https://ditfjx9w4x3vl.cloudfront.net/assets/header/products/pc/2.0-S.jpg','Impressora FDM da Snapmaker',100),
('Snapmaker','Snapmaker 2.0 A350','fdm','https://ditfjx9w4x3vl.cloudfront.net/assets/header/products/pc/2.0-S.jpg','Impressora FDM da Snapmaker',100),
('Snapmaker','Artisan','fdm','https://cdn.snapmaker.com/images/products/artisan/artisan-product.png','Impressora FDM da Snapmaker',100),
('Snapmaker','J1s','fdm','https://cdn.snapmaker.com/images/products/j1s/j1s-product.png','Impressora FDM da Snapmaker',100),
('Snapmaker','U1','fdm','https://ditfjx9w4x3vl.cloudfront.net/config/images/u1-20260324-G%20(4).png','Impressora FDM da Snapmaker',100),
('Voron Design','Voron 0.2','fdm','https://vorondesign.com/image/voron0.2.png','Impressora FDM da Voron Design',100),
('Voron Design','Voron Trident','fdm','https://vorondesign.com/image/vorontrident.png','Impressora FDM da Voron Design',100),
('Voron Design','Voron 2.4','fdm','https://vorondesign.com/image/voron2.4.png','Impressora FDM da Voron Design',100),
('Voron Design','Voron Switchwire','fdm','https://vorondesign.com/image/voron2.4.png','Impressora FDM da Voron Design',100),
('Raise3D','Pro3','fdm','https://www.raise3d.com/wp-content/uploads/2021/03/pro3-product.png','Impressora FDM da Raise3D',100),
('Raise3D','Pro3 Plus','fdm','https://www.raise3d.com/wp-content/uploads/2021/03/pro3plus-product.png','Impressora FDM da Raise3D',100),
('Raise3D','E2','fdm','https://www.raise3d.com/wp-content/uploads/2021/03/e2-product.png','Impressora FDM da Raise3D',100),
('Raise3D','E2CF','fdm','https://www.raise3d.com/wp-content/uploads/2021/03/e2cf-product.png','Impressora FDM da Raise3D',100),
('Raise3D','N4','fdm','https://www.raise3d.com/wp-content/uploads/2021/03/n4-product.png','Impressora FDM da Raise3D',100),
('Ultimaker','S3','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/s-series/ultimaker-s3/images/ultimaker-s3-front.png','Impressora FDM da Ultimaker',100),
('Ultimaker','S5','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/s-series/ultimaker-s5/images/ultimaker-s5-front.png','Impressora FDM da Ultimaker',100),
('Ultimaker','S7','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/s-series/ultimaker-s7/images/ultimaker-s7-front.png','Impressora FDM da Ultimaker',100),
('Artillery','Sidewinder X4 Pro','fdm','https://artillery3d.com/cdn/shop/products/sidewinder-x4-pro_800x.png','Impressora FDM da Artillery',100),
('Artillery','Genius Pro','fdm','https://artillery3d.com/cdn/shop/products/genius-pro_800x.png','Impressora FDM da Artillery',100),
('Artillery','Hornet','fdm','https://artillery3d.com/cdn/shop/products/hornet_800x.png','Impressora FDM da Artillery',100),
('Sovol','SV06','fdm','https://sovol3d.com/cdn/shop/files/SV06_1.png','Impressora FDM da Sovol',100),
('Sovol','SV06 Plus','fdm','https://sovol3d.com/cdn/shop/files/SV06Plus_1.png','Impressora FDM da Sovol',100),
('Sovol','SV07','fdm','https://sovol3d.com/cdn/shop/files/SV07_1.png','Impressora FDM da Sovol',100),
('Sovol','SV08','fdm','https://sovol3d.com/cdn/shop/files/SV08_1.png','Impressora FDM da Sovol',100),
('Phrozen','Sonic Mini 8K','resina','https://phrozen3d.com/cdn/shop/products/sonic-mini-8k-product.png','Impressora RESINA da Phrozen',100),
('Phrozen','Sonic Mega 8K','resina','https://phrozen3d.com/cdn/shop/products/sonic-mega-8k-product.png','Impressora RESINA da Phrozen',100),
('Phrozen','Sonic Mighty 8K','resina','https://phrozen3d.com/cdn/shop/products/sonic-mighty-8k.png','Impressora RESINA da Phrozen',100),
('Phrozen','Transform 12K','resina','https://phrozen3d.com/cdn/shop/products/transform-12k.png','Impressora RESINA da Phrozen',100),
('Formlabs','Form 3','resina','https://formlabs.com/media/form3-printer.png','Impressora RESINA da Formlabs',100),
('Formlabs','Form 3+','resina','https://formlabs.com/media/form3plus-printer.png','Impressora RESINA da Formlabs',100),
('Formlabs','Form 3L','resina','https://formlabs.com/media/form3l-printer.png','Impressora RESINA da Formlabs',100),
('Formlabs','Form 4','resina','https://formlabs.com/media/form4-printer.png','Impressora RESINA da Formlabs',100),
('Formlabs','Form 4L','resina','https://formlabs.com/media/form4l-printer.png','Impressora RESINA da Formlabs',100),
('Zortrax','M200 Plus','fdm','https://zortrax.com/wp-content/uploads/2025/11/M200-Plus-Front.png','Impressora FDM da Zortrax',100),
('Zortrax','M300 Dual','fdm','https://zortrax.com/wp-content/uploads/2025/11/M300-Dual-Front.png','Impressora FDM da Zortrax',100),
('Zortrax','E3','fdm','https://zortrax.com/wp-content/uploads/e3-front.png','Impressora FDM da Zortrax',100),
('Zortrax','Inkspire 2','resina','https://zortrax.com/wp-content/uploads/2025/10/Inkspire-2-Front.png','Impressora RESINA da Zortrax',100),
('BCN3D','Epsilon W27','fdm','https://www.bcn3d.com/wp-content/uploads/2025/07/BCN3D-Epsilon-W27-Front.png','Impressora FDM da BCN3D',100),
('BCN3D','Epsilon W50','fdm','https://www.bcn3d.com/wp-content/uploads/2025/07/BCN3D-Epsilon-W50-Front.png','Impressora FDM da BCN3D',100),
('BCN3D','Omega I60','fdm','https://www.bcn3d.com/wp-content/uploads/2025/03/BCN3D-Omega-I60-Front.png','Impressora FDM da BCN3D',100),
('Stratasys','F123CR','fdm','https://www.stratasys.com/siteassets/3d-printers/f123-series/f123cr-product.png','Impressora FDM da Stratasys',100),
('Stratasys','F370CR','fdm','https://www.stratasys.com/siteassets/3d-printers/f123-series/f370cr-product.png','Impressora FDM da Stratasys',100),
('Stratasys','Fortus 380','fdm','https://www.stratasys.com/siteassets/3d-printers/fortus/fortus380-product.png','Impressora FDM da Stratasys',100),
('Stratasys','Origin One','resina','https://www.stratasys.com/siteassets/3d-printers/origin/origin-one-product.png','Impressora RESINA da Stratasys',100),
('MakerBot','METHOD X','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/method-series/method-x/images/method-x-front.png','Impressora FDM da MakerBot',100),
('MakerBot','METHOD XL','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/method-series/method-xl/images/method-xl-front.png','Impressora FDM da MakerBot',100),
('MakerBot','SKETCH','fdm','https://ultimaker.com/cdn-cgi/image/width=1000,f=auto/3d-printers/sketch-series/sketch/images/sketch-front.png','Impressora FDM da MakerBot',100);

-- ✅ Total: 119 | Com imagem: 119 | Sem imagem: 0
